security:
  oauth2:
    client:
      clientId: account-service
      clientSecret: ${ACCOUNT_SERVICE_PASSWORD}
      accessTokenUri: http://auth-service:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://account-postgres:5432/${ACCOUNT_POSTGRES_DB_NAME}
    username: postgres
    password: ${POSTGRESDB_PASSWORD}

server:
  servlet:
    context-path: /accounts
  port: 6000

feign:
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: refresh
